(function(a){var b={};function c(e){if(b[e]){return b[e].exports;}var d=b[e]={exports:{},id:e,loaded:false};a[e].call(d.exports,d,d.exports,c);d.loaded=true;
return d.exports;}c.m=a;c.c=b;c.p="./js/";return c(0);})([function(b,a,c){b.exports=c(1);},function(d,c,h){var g=h(2);var e=h(4);var b=h(5);var a=h(6);
var f=h(8);"use strict";window.onload=function(){var i=$(window).width();var j=$("body").attr("data-design-width");var l=$("body").attr("data-design-dpr");
$("html").attr("data-dpr",window.devicePixelRatio);if(!j){j=640;}if(!l){l=2;}setTimeout(function(){q=$(window).width();if(q>j){q=j;}$("html").css("font-size",100/(j/l)*q+"px");
var v=$(".event-bar ul");var t=$(".event-bar li");var n=$(".book ul");var p=$(".book li");var q=$(window).width();var u=null;for(var s=0;s<t.length;s++){u+=$(".event-bar li").eq(s)[0].clientWidth;
}p.each(function(){if($(this).index()>2&&$(this).index()<p.length-1){$(this).addClass("hide");}});$(".more-date").click(function(){p.removeClass("hide");
$(this).addClass("hide");});$(".location").click(function(){window.location.href=this.dataset.href;});$(".map-stop").click(function(){window.location.href=this.dataset.href;
});u+=s;v.width(u);if(u>=q){$(".event-bar").addClass("NMSlider");}$(".header .left").click(function(){window.history.back();});var m=new f.NMDetailPhotoAlbum($(".nm-photo-album")[0]);
var o=$(".user-comment-li .photo");o.each(function(){new a.NMDataToPhotoAlbum(this,$(".nm-photo-album")[0]);});var r=new a.NMDataToPhotoAlbum($(".face-photo")[0],$(".nm-photo-album")[0]);
$(".face-photo").click(function(){r.bindThis();});$(".sport-facilities .album").click(function(){r.bindThis($(this).attr("data-index")-1);});$(".serve-facilities .album").click(function(){r.bindThis($(this).attr("data-index")-1);
});$(".qu-zone").click(function(){$(".nm-cover").removeClass("hide");$(".nm-alert").addClass("hide");$(".nm-cover .download").removeClass("hide");});$(".downloadapp").click(function(){window.location.href="http://www.quyundong.com/d";
$(".nm-cover").addClass("hide");});$(".nm-cover .cancel").click(function(){$(".nm-cover").addClass("hide");});$(".more-info").click(function(){$(this).addClass("hide");
$(".info-serve").removeClass("hide");});$(".NMSlider").each(function(){var y=new g.NMSlider(this);var x=$(this).find("li");x.each(function(w){if($(this).find("a").hasClass("cur")){y.set(w*-this.clientWidth);
}});});},100);$(window).resize(function(){i=$(window).width();if(i>j){i=j;}$("html").css("font-size",100/(j/l)*i+"px");});var k=setInterval(function(){if($(".loading").attr("data-lock")==1){$(".loading").addClass("hide");
$(".detail-main").removeClass("hide");clearInterval(k);}},500);};$(document).ready(function(){var i=$(".detail-stars");$(".detail-stars").each(function(){new e.NMStars(this);
});(0,b.dprImagesFixed)();$(".person-card").click(function(j){if(!$(j.target).hasClass("buy")){if(this.dataset.href){window.location.href=this.dataset.href;
}}else{if(j.target.dataset.href){window.location.href=j.target.dataset.href;}}});});},function(b,a,e){Object.defineProperty(a,"__esModule",{value:true});
a.NMSlider=undefined;var c=e(3);function d(f){this.dom=f;this.init();this.bindEvent();}d.prototype.init=function(){this.ul=$(this.dom).find("ul")[0];this.width=this.ul.clientWidth;
this.ul.style.width=this.width+"px";this.domWidth=this.dom.clientWidth;this.lastOffset=0;this.changeX=0;this.end=false;};d.prototype.bindEvent=function(){var f=function f(i){this.startTime=new Date()*1;
this.end=false;if(i.touches){this.startX=i.touches[0].pageX;}else{this.startX=i.pageX;}this.offsetX=0;}.bind(this);var g=function g(i){i.preventDefault();
if(!!this.end){return false;}if(i.touches){this.offsetX=i.targetTouches[0].pageX-this.startX;}else{this.offsetX=i.pageX-this.startX;}if(this.offsetX+this.lastOffset<=0&&this.offsetX+this.lastOffset>=-(this.width-this.domWidth)){this.changeX=this.offsetX+this.lastOffset;
}this.ul.style.webkitTransform="translate3d("+this.changeX+"px, 0, 0)";this.ul.style.transform="translate3d("+this.changeX+"px, 0, 0)";}.bind(this);var h=function h(j){var i=new Date()*1;
this.end=true;if(!(0,c.isAnimation)(this.ul)){if(i-this.startTime<=300&&this.offsetX>0){this.changeX=0;$(this.ul).animate({transform:"translate3d("+this.changeX+"px,0,0)","webkit-transform":"translate3d("+this.changeX+"px,0,0)"},300,"linear",0);
}else{if(i-this.startTime<=300&&this.offsetX<0){this.changeX=-this.width+this.domWidth;$(this.ul).animate({transform:"translate3d("+this.changeX+"px,0,0)","webkit-transform":"translate3d("+this.changeX+"px,0,0)"},300,"linear",0);
}}}this.lastOffset=this.changeX;}.bind(this);this.dom.addEventListener("touchstart",f);this.dom.addEventListener("touchmove",g,false);this.dom.addEventListener("touchend",h,false);
this.dom.addEventListener("click",function(){},false);};d.prototype.set=function(f){if(f<-(this.width-this.domWidth)){f=-(this.width-this.domWidth);}else{if(f>0){f=0;
}}this.lastOffset=f;this.ul.style.webkitTransform="translate3d("+f+"px, 0, 0)";this.ul.style.transform="translate3d("+f+"px, 0, 0)";};a.NMSlider=d;},function(c,b){Object.defineProperty(b,"__esModule",{value:true});
function a(d){return !!($(d).attr("style").indexOf("transition")!=-1||$(d).attr("style").indexOf("webkitTransition")!=-1);}b.isAnimation=a;},function(b,a){Object.defineProperty(a,"__esModule",{value:true});
function c(d){this.dom=d;this.init();this.render();}c.prototype.init=function(){this.point=this.dom.dataset.point*1;this.showPoint=this.dom.dataset.showpoint;
this.totle=5;this.fullSrc=this.dom.dataset.fullSrc;this.emptySrc=this.dom.dataset.emptySrc;if(this.point>=this.totle){this.stars=this.totle;}else{if(this.point<=0){this.stars=0;
}else{this.stars=parseInt(this.point);}}};c.prototype.render=function(){var g=[];for(var f=0;f<this.totle;f++){g[f]=document.createElement("i");g[f].innerHTML="<img data-src='"+this.emptySrc+"' />";
}if(this.showPoint=="true"){g[f]=document.createElement("span");g[f].innerHTML=this.point+"分";}for(var e=0;e<this.stars;e++){g[e].innerHTML="<img data-src='"+this.fullSrc+"' />";
}for(var d=0;d<g.length;d++){this.dom.appendChild(g[d]);}};a.NMStars=c;},function(c,a){Object.defineProperty(a,"__esModule",{value:true});function b(){var d=window.devicePixelRatio*1;
$("img").each(function(){var e;if(d>2){e="dpr3x";}else{e="dpr2x";}if(this.getAttribute("data-src")){var f=this.getAttribute("data-src").replace(/dpr2x/,e);
this.src=f;}});$(".use-background").each(function(){var e;if(d>2){e="dpr3x";}else{e="dpr2x";}if(this.getAttribute("data-src")&&this.getAttribute("data-src")!="url()"){var f=this.getAttribute("data-src").replace(/dpr2x/,e);
this.style.backgroundImage=f;}});}a.dprImagesFixed=b;},function(d,b,e){Object.defineProperty(b,"__esModule",{value:true});b.NMDataToPhotoAlbum=undefined;
var c=e(7);function a(g,f){this.targetDom=g;this.albumDom=f;this.$images=$(this.targetDom).find("img");this.title=this.targetDom.dataset.title;this.bindEvent();
}a.prototype.insert=function(){var j=this;$(this.albumDom).find("ul").remove();this.ul=document.createElement("ul");this.albumDom.appendChild(this.ul);
$(this.albumDom).find("ul").html("");this.domList=[];$(this.albumDom).find("ul").css("width",100*this.$images.length+"%");var g=this;var h=function h(m){var k=document.createElement("li");
var n=document.createElement("div");var l=document.createElement("img");k.style.width=100/j.$images.length+"%";l.onload=function(){var i=l.width/l.height;
var o=$(window).width()/$(window).height();if(i>=o){n.style.width="100%";}else{n.style.width=l.width*$(window).height()/l.height+"px";n.style.height="100%";
}};l.src=g.$images[m].dataset.bigSrc;k.appendChild(n);n.appendChild(l);g.domList.push(k);};for(var f=0;f<this.$images.length;f++){h(f);}for(var f=0;f<this.domList.length;
f++){$(this.albumDom).find("ul")[0].appendChild(g.domList[f]);}};a.prototype.render=function(f){var f=f||0;$(this.albumDom).removeClass("hide");this.albumDom.scrollY=window.scrollY;
$(this.albumDom).find(".index").html(f*1+1);$(this.albumDom).find(".totle").html(this.$images.length);$(this.albumDom).find(".title").html(this.title);
this.insert();};a.prototype.bindEvent=function(){var f=this;this.$images.each(function(g){this.addEventListener("click",function(){f.render(g);new c.NMPhotoSlider(f.ul,g,$(f.albumDom).find(".index")[0]);
},false);});};a.prototype.bindThis=function(f){var f=f||0;this.render();new c.NMPhotoSlider(this.ul,f,$(this.albumDom).find(".index")[0]);};b.NMDataToPhotoAlbum=a;
},function(b,a,e){Object.defineProperty(a,"__esModule",{value:true});a.NMPhotoSlider=undefined;var c=e(3);function d(h,g,f){this.dom=h;this.indexLocation=f;
this.index=g||0;this.init();this.bindEvent();}d.prototype.init=function(){this.indexLocation.innerHTML=this.index*1+1;this.width=this.dom.clientWidth*1;
this.liWidth=this.dom.childNodes[0].clientWidth;this.totle=this.dom.childNodes.length;this.dom.style.width=this.width+"px";this.windowWidth=$(window).width();
this.lastOffset=this.index*-1*(this.width/this.dom.childNodes.length);this.changeX=0;this.end=false;this.isMove=false;this.dom.style.webkitTransform="translate3d("+this.lastOffset+"px, 0, 0)";
this.dom.style.transform="translate3d("+this.lastOffset+"px, 0, 0)";};d.prototype.bindEvent=function(){var f=function f(i){i.preventDefault();this.startTime=new Date()*1;
this.end=false;if(i.touches){this.startX=i.touches[0].pageX;}else{this.startX=i.pageX;}}.bind(this);var g=function g(i){i.preventDefault();this.isMove=true;
if(!!this.end){return false;}if(i.touches){this.offsetX=i.targetTouches[0].pageX-this.startX;}else{this.offsetX=i.pageX-this.startX;}this.changeX=this.offsetX+this.lastOffset;
if(this.changeX>=0){this.changeX=0;}else{if(this.changeX<=-(this.width-this.windowWidth)){this.changeX=-(this.width-this.windowWidth);}}this.dom.style.webkitTransform="translate3d("+this.changeX+"px, 0, 0)";
this.dom.style.transform="translate3d("+this.changeX+"px, 0, 0)";}.bind(this);var h=function h(k){k.preventDefault();var i=new Date()*1;this.end=true;if(i-this.startTime<200&&!this.isMove){var j=this;
setTimeout(function(){j.dom.parentNode.className+=" hide";j.dom.parentNode.hideCallback&&j.dom.parentNode.hideCallback();window.scrollTo(0,j.dom.parentNode.scrollY);
},0);}if(!(0,c.isAnimation)(this.dom)&&this.changeX-this.lastOffset!=0){if(i-this.startTime<=300&&this.offsetX>0||Math.abs(this.offsetX)>=this.liWidth/6&&this.offsetX>0){this.index=this.index-1;
if(this.index<0){this.index=0;}}else{if(i-this.startTime<=300&&this.offsetX<0||Math.abs(this.offsetX)>=this.liWidth/6&&this.offsetX<0){this.index=this.index*1+1;
if(this.index>this.totle-1){this.index=this.totle-1;}}}this.changeX=this.index*-this.liWidth;this.indexLocation.innerHTML=this.index*1+1;$(this.dom).animate({transform:"translate3d("+this.changeX+"px,0,0)","-webkit-transform":"translate3d("+this.changeX+"px,0,0)"},300,"linear",0);
}this.lastOffset=this.changeX;this.isMove=false;}.bind(this);this.dom.addEventListener("touchstart",f,false);this.dom.addEventListener("touchmove",g,false);
this.dom.addEventListener("touchend",h,false);};a.NMPhotoSlider=d;},function(b,a){Object.defineProperty(a,"__esModule",{value:true});function c(d){this.dom=d;
this.init();}c.prototype.init=function(){var d=this;$(this.dom).find(".close").click(function(){$(d.dom).find("ul").remove();$(d.dom).addClass("hide");
d.dom.hideCallback&&d.dom.hideCallback();window.scrollTo(0,d.scrollY);});};a.NMDetailPhotoAlbum=c;}]);